logging:
  level:
    com.example.recommendation.external.naver: DEBUG
    org.springframework.web.client: DEBUG

server:
  forward-headers-strategy: framework
  servlet:
    session:
      cookie:
        same-site: NONE
        secure: true
